version: "3"
services:
  php:
    build: "./php"
    volumes: 
      - ./code:/var/www/html
    networks: 
      - php-service
  nginx:
    build: "./nginx"
    volumes: 
      - ./code:/var/www/html
    ports:
      - "8080:80"
    networks: 
      - php-service
  db:
    build: "./mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_DATABASE: "user"
      MYSQL_ROOT_PASSWORD: "1qaz2wsx3edc"
    networks: 
      - php-service
networks: 
  php-service: